=== Tusamarco/proxysqlcp/proxygui/display/template/ncp/ncpreportf.dtd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Marco Tusa (F.A.O. (Div. AFIS)) --><!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><!ELEMENT Country (name, longname)><!ATTLIST Country	faostatcode CDATA #REQUIRED	iso3 CDATA #REQUIRED><!ELEMENT NCPReport (Country, Theme+)><!ATTLIST NCPReport	id CDATA #REQUIRED	languageofproduction CDATA #REQUIRED	yearofproduction CDATA #REQUIRED><!ELEMENT Textual (picture?, dataset?, text?)><!ATTLIST Textual	id (2853 | 2855 | 2857 | 2859 | 2861 | 2863 | 2904 | 2946 | 2948) #REQUIRED	type CDATA #REQUIRED	style CDATA #REQUIRED	order (0 | 1 | 2 | 3 | 4 | 5) #REQUIRED	name CDATA #REQUIRED><!ELEMENT Theme (Textual*)><!ATTLIST Theme	id (2864 | 2872 | 2876 | 2880 | 2892 | 2896 | 2905 | 2913 | 2919 | 2927 | 2931 | 2935 | 2939 | 2943 | 2949 | 2953 | 2967 | 2989 | 2995 | 3003 | 3009 | 3013) #REQUIRED	position CDATA #REQUIRED	order (0 | 1 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 2 | 20 | 21 | 3 | 4 | 5 | 6 | 7 | 8 | 9) #REQUIRED	name CDATA #REQUIRED><!ELEMENT comment (#PCDATA)><!ELEMENT country EMPTY><!ATTLIST country	name CDATA #REQUIRED><!ELEMENT dataset (comment?, note?, xml?, region*)><!ATTLIST dataset	id (2903 | 3139) #IMPLIED	type CDATA #IMPLIED	style (dasd | ncpdataset) #IMPLIED	order (0 | 1) #IMPLIED	name CDATA #REQUIRED	datasetid CDATA #IMPLIED	heading CDATA #IMPLIED	themeid CDATA #IMPLIED><!ELEMENT datasets (country, layer)><!ELEMENT extent (extent+ | year)><!ATTLIST extent	axis (2 | 3 | 4 | 5 | 6 | 7) #REQUIRED	heading CDATA #REQUIRED	name CDATA #REQUIRED><!ELEMENT layer (dataset)><!ATTLIST layer	heading CDATA #REQUIRED	name CDATA #REQUIRED><!ELEMENT longname (#PCDATA)><!ELEMENT name (#PCDATA)><!ELEMENT note (#PCDATA)><!ELEMENT picture (#PCDATA)><!ATTLIST picture	id CDATA #REQUIRED	type CDATA #REQUIRED	style CDATA #REQUIRED	order CDATA #REQUIRED	name CDATA #REQUIRED><!ELEMENT region (extent+)><!ATTLIST region	heading CDATA #REQUIRED	layername CDATA #REQUIRED	name (Antananarivo | Antsiranana | Fianarantsoa | Mahajanga | Toamasina | Toliary) #REQUIRED><!ELEMENT text (#PCDATA)><!ATTLIST text	id CDATA #REQUIRED	type CDATA #REQUIRED	style CDATA #REQUIRED	order CDATA #REQUIRED	name CDATA #REQUIRED><!ELEMENT xml (datasets)><!ELEMENT year EMPTY><!ATTLIST year	Publishyear CDATA #REQUIRED	name (1992 | 1997 | 2003-2004) #REQUIRED	sample_defn_idx (0 | 1 | 10 | 11 | 12 | 13 | 14 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9) #REQUIRED	sample_size (1273 | 211 | 214 | 396 | 431 | 436 | 451 | 514 | 523 | 643 | 655 | 830 | 968) #REQUIRED	value (0.1 | 0.2 | 0.6 | 0.7 | 0.8 | 1.2 | 1.8 | 11.1 | 11.4 | 11.8 | 12.2 | 12.4 | 13.4 | 13.5 | 14.0 | 14.3 | 15.0 | 15.1 | 15.3 | 15.6 | 15.8 | 16.2 | 16.4 | 16.5 | 16.6 | 18.7 | 2.5 | 20.2 | 23.6 | 24.5 | 25.7 | 27.8 | 27.9 | 28.1 | 3.2 | 3.3 | 3.8 | 31.5 | 31.8 | 32.6 | 34.2 | 34.3 | 36.5 | 37.1 | 38.9 | 39.3 | 39.6 | 39.7 | 39.9 | 4.2 | 4.4 | 40.2 | 41.0 | 41.5 | 43.8 | 44.1 | 44.6 | 44.7 | 45.7 | 47.8 | 48.5 | 5.4 | 5.7 | 5.8 | 50.1 | 51.6 | 57.0 | 6.0 | 6.4 | 61.4 | 7.1 | 7.2 | 7.5 | 7.6 | 7.9 | 8.6 | 8.7 | 9.3 | 9.9) #REQUIRED>

=== Tusamarco/proxysqlcp/proxygui/display/template/ncp/reporttest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NCPReport SYSTEM "ncpreportf.dtd">
<NCPReport id="2850" languageofproduction="en" yearofproduction="2005">
	<Country faostatcode="129" iso3="MDG">
		<name>Madagascar</name>
		<longname>Madagascar</longname>
	</Country>
	<Theme id="2905" position="top" order="0" name="Nutrition Profile">
		<Textual id="2904" type="1" style="outlineelement" order="0" name="Location of Country">
			<dataset id="2903" type="2" style="ncpdataset" order="0" name="testData">
				<xml>
					<datasets>
						<country name="Madagascar"/>
						<layer heading="layer" name="Admin 1">
							<dataset datasetid="" heading="theme" name="Anthropometric surveys of preschool children" themeid="">
								<region heading="Region" layername="Admin 1" name="Antananarivo">
									<extent axis="2" heading="Source Name" name="EnquÃªte DÃ©mographique et de SantÃ© Madagascar 1997 (DDSS/INSTAT and Macro Int.Inc.">
										<extent axis="3" heading="Residence" name="unspecified">
											<extent axis="4" heading="Age" name="0 - 2.99">
												<extent axis="5" heading="Gender" name="M/F">
													<extent axis="6" heading="Mother's Education" name="unspecified">
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age &lt;-3 Z-scores">
															<year Publishyear="2005" name="1997" sample_defn_idx="2" sample_size="968" value="25.7"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1997" sample_defn_idx="2" sample_size="968" value="57.0"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-3 Z-scores">
															<year Publishyear="2005" name="1997" sample_defn_idx="2" sample_size="968" value="0.8"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1997" sample_defn_idx="2" sample_size="968" value="7.9"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-3 Z-scores">
															<year Publishyear="2005" name="1997" sample_defn_idx="2" sample_size="968" value="15.1"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1997" sample_defn_idx="2" sample_size="968" value="43.8"/>
														</extent>
													</extent>
												</extent>
											</extent>
										</extent>
									</extent>
									<extent axis="2" heading="Source Name" name="EnquÃªte DÃ©mographique et de SantÃ© de Madagascar 2003-2004 (INSTAT et ORC Macro">
										<extent axis="3" heading="Residence" name="unspecified">
											<extent axis="4" heading="Age" name="0 - 2.99">
												<extent axis="5" heading="Gender" name="M/F">
													<extent axis="6" heading="Mother's Education" name="unspecified">
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age &lt;-3 Z-scores">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="9" sample_size="830" value="27.9"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="9" sample_size="830" value="50.1"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-3 Z-scores">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="9" sample_size="830" value="2.5"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-2 Z-scores*">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="9" sample_size="830" value="12.2"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-3 Z-scores">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="9" sample_size="830" value="11.1"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="9" sample_size="830" value="39.3"/>
														</extent>
													</extent>
												</extent>
											</extent>
										</extent>
									</extent>
									<extent axis="2" heading="Source Name" name="EnquÃªte nationale dÃ©mographique et sanitaire 1992. (Refeno G.">
										<extent axis="3" heading="Residence" name="unspecified">
											<extent axis="4" heading="Age" name="0 - 4.99">
												<extent axis="5" heading="Gender" name="M/F">
													<extent axis="6" heading="Mother's Education" name="unspecified">
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age &lt;-3 Z-scores">
															<year Publishyear="2005" name="1992" sample_defn_idx="7" sample_size="1273" value="27.8"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1992" sample_defn_idx="7" sample_size="1273" value="61.4"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-3 Z-scores">
															<year Publishyear="2005" name="1992" sample_defn_idx="7" sample_size="1273" value="0.1"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1992" sample_defn_idx="7" sample_size="1273" value="3.2"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-3 Z-scores">
															<year Publishyear="2005" name="1992" sample_defn_idx="7" sample_size="1273" value="8.6"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1992" sample_defn_idx="7" sample_size="1273" value="44.7"/>
														</extent>
													</extent>
												</extent>
											</extent>
										</extent>
									</extent>
								</region>
								<region heading="Region" layername="Admin 1" name="Antsiranana">
									<extent axis="2" heading="Source Name" name="EnquÃªte DÃ©mographique et de SantÃ© Madagascar 1997 (DDSS/INSTAT and Macro Int.Inc.">
										<extent axis="3" heading="Residence" name="unspecified">
											<extent axis="4" heading="Age" name="0 - 2.99">
												<extent axis="5" heading="Gender" name="M/F">
													<extent axis="6" heading="Mother's Education" name="unspecified">
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age &lt;-3 Z-scores">
															<year Publishyear="2005" name="1997" sample_defn_idx="14" sample_size="211" value="15.0"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1997" sample_defn_idx="14" sample_size="211" value="37.1"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-3 Z-scores">
															<year Publishyear="2005" name="1997" sample_defn_idx="14" sample_size="211" value="0.6"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1997" sample_defn_idx="14" sample_size="211" value="4.2"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-3 Z-scores">
															<year Publishyear="2005" name="1997" sample_defn_idx="14" sample_size="211" value="7.5"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Underweight:Weight-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="1997" sample_defn_idx="14" sample_size="211" value="31.8"/>
														</extent>
													</extent>
												</extent>
											</extent>
										</extent>
									</extent>
									<extent axis="2" heading="Source Name" name="EnquÃªte DÃ©mographique et de SantÃ© de Madagascar 2003-2004 (INSTAT et ORC Macro">
										<extent axis="3" heading="Residence" name="unspecified">
											<extent axis="4" heading="Age" name="0 - 2.99">
												<extent axis="5" heading="Gender" name="M/F">
													<extent axis="6" heading="Mother's Education" name="unspecified">
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age &lt;-3 Z-scores">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="5" sample_size="214" value="14.3"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Stunting:Height-for-age&lt;-2 Z-scores*">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="5" sample_size="214" value="31.5"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-3 Z-scores">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="5" sample_size="214" value="1.8"/>
														</extent>
														<extent axis="7" heading="Indicator" name="Wasting:Weight-for-height&lt;-2 Z-scores*">
															<year Publishyear="2005" name="2003-2004" sample_defn_idx="5" sample_size="214" value="14.0"/>
														</extent>
